platform:ios,"8.3"
use_frameworks!
target 'PbSwiftLibrary' do
    pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift', :branch => "feature/ios10"
   pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "swift3"
end
